import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
 

// Import the Open Sans font from `next/font/google`
import { Inter } from 'next/font/google';
import Navbar from "@/components/navbar";

// Configure the font object
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       
      <body
        className={` antialiased ${inter.className} bg-gray-100`}
        style={{ 
          backgroundColor: "white",
          backgroundImage: `linear-gradient(to right, rgba(0, 0, 0, 0.1) 1px, transparent 1px),
              linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 1px, transparent 1px)`,
          backgroundSize: `50px 50px` /* Adjust grid cell size */,
        } }
      >
      <Navbar />

        <ThemeProvider attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
